### ISSUE TITLE
Redis and Feathers service API are butting heads

### ISSUE THREAD

**Issue by appurist** [feathersjs-ecosystem/feathers-redis#4]
**Problem**
Redis is fast because it is like the "RISC" implementation of databases.  A reduced number of operations, and simplification where _everything_ is based on the _IDs_ for the records; the _only_ keys are the IDs.  Only the record IDs/keys can be searched using a pattern.

As a result, there is _no_ search by other criteria, unless the fields to be searchable have been extracted and built a separate parallel namespace ("table") of ID keys with the _values_ for the original fields stored as the IDs to the index records.  i.e. The caller must manually create an index for each searchable field, otherwise the only query option is to load the whole database and do a linear search over _all records_, or at least those that match a certain key namespace (i.e. table), like "users:*".

Basically, Redis provides some very cool db storage types, like '_hash_' and '_set_' (ideal for indices), as building blocks for this, and assumes the db administrator creates ID-based records appropriate for needs.  There is no inherent search by criteria other than by IDs.

**Solutions**
To provide a Redis service adapter for **_Feathers_**, there are a couple of options:
1. Auto-construct and _consistently maintain_ parallel "system index tables" for each query-ready field in a caller record (e.g. for all fields in all records).
2. Search for efficiently for matching IDs if a query happens to be limited to the `id` field, otherwise inefficiently search _all_ records for matching criteria (linear search).
3. Limit the queries to the `id` field.

#1 is very intrusive for an adapter, that is intrusive for it to do that in the caller's db. In fact I'd be pretty annoyed if I called feathers-redis functions and it started adding records beyond the ones explicitly indicated in a create.  We could do this, but another problem is that it would also not support existing Redis databases. This adapter would need to be used as the database access mechanism and the only (exclusive) such service with access to the db data.  Or for existing data, it would have to run some kind of index builder before you could issue finds.  I think this is prohibitively horrible.

#2 isn't a bad approach although it runs the risk of failures due to exhausting memory if the data set is large and the caller finds the query facilities _convenient_.  It _hides_ the complexity of providing and supporting a Redis database, in a potentially dangerous way.

#3 actually matches Redis functionality.  More complex queries are supported the Redis way, by adding more keys in a parallel "index" of records.  Thus, you can't query on the phoneNumber field if you haven't created an index with phoneNumber:nnn for IDs.

**Proposal**
In the initial version, I'm going to go with #3 and limit the find criteria to ID fields.  We could extend this for small databases but even if they do this via feathers-redis, they could and should be using feathers-redis to add more indexed data.  

Unfortunately the '_set_' Redis data type is ideal for this, but cannot be used since we only have `get` and `set` operations (for a single type).  Redis has a whole _families_ of `set`-commands.  There isn't even an `options` parameter passed on these operations where we could indicate an alternate type of data (e.g. to store an object of fields names and values as a Redis '_hash_') or in this case as a '_set_'.  But string or JSON-based records could still be used; it's not ideal but it's what we can support via the generic interface.  

**Future**
We might also be able to recognize special object fields (as we do now for `id` or `_id`, etc) for Redis types or options specification.  Or, if `set` also accepted a recognized object, with two members: `redis` (with options) and `data` (the actual record data), or `feathersOptions` and `feathersData`. So for example, `feathersOptions` could indicate that the data is a Redis '_list_' or '_set_' and then accept an array in `feathersData`, or `feathersOptions` could indicate that the data is a Redis '_hash_' and then accept an object full of fields and values in `feathersData`. I beleive this could be done in a backwards-compatible way with existing calls and code.

For background understanding of how Redis is used for more complete general queries, see [this article](http://tylerstroud.com/2014/11/18/storing-and-querying-objects-in-redis/) as a good example.

**Comment by appurist** [comment]
Note, I don't like the **Future** stuff above, because it violates the whole purpose of feathers db adapters maintaining a consistent cross-adapter implementation.  I don't really like option 2 above because it hides a huge performance hit.  

However, other feathers contributors may have already encountered this dilemma and established a philosophy on it. I'm very open to suggestions or alternatives, and I do think maintaining consistency across adapters is a primary objective.  So if others are resolving queries via linear searches, feathers-redis could do so as well. 

Redis does support paging directly, so memory during a query could be controlled (except for the matching records of course).

**Comment by appurist** [comment]
It seems others have commented on this problem in a more general way:
[The SELECT problem in redis](http://www.federicopereiro.com/redis-select/)

**Comment by appurist** [comment]
There is a second issue with Redis in relation to paging.  When a query does not include all records, it will return _less records than specified_ by a `$limit` option, however it will include a non-zero scan cursor position to indicate that more data is available in the next iteration.  In fact, it is also quite common for Redis to return _more than_ the count specified.  Thus if the Feathers service interface's paging options are fairly rigid, and stateless, it's not really possible to provide the data paged, at least not without rescanning from _the start_ at each iteration.

I think the only way to implement `$skip` and `$limit` is to either buffer all results (but it's stateless so perhaps in a LRU cache) or, more likely, to scan from the beginning of the data each time and pluck and return only the records that match the paging criteria.

Also worth noting that the `$skip` value does not correspond to the Redis cursor in any way.  Note the [example here](http://redis.io/commands/scan) where the first scan for 10 items actually returned 11 items and a new cursor value of 17 for the next page. It returned 0 on the second scan indicating it was the final page.

Suggestions? We could just say that pagination (and non-ID queries too) are horribly inefficient in feathers-redis and to be avoided, but there are serious architectural conflicts here with Redis, to the point where almost all the capabilities and benefits of using Redis (square peg) are negated by trying to force it through the Feathers services interface (in this case, a round hole).

**Comment by appurist** [comment]
Actually that linear search for paging may not be so bad. It's only a scan through all records to extract _the IDs_ of the target page.  That's probably still fast and uses little memory.  But to provide strict (i.e. correct) $skip and $limit implementations, we'd need to scan the keys (IDs) from the beginning on each call.  (That's what I'll do.)

**Comment by ekryski** [comment]
@appurist really nice writeup and detailed thoughts. 🍻 

A couple of mine:

> In the initial version, I'm going to go with #3 and limit the find criteria to ID fields. We could extend this for small databases but even if they do this via feathers-redis, they could and should be using feathers-redis to add more indexed data.

I agree and I think this is the best approach. At least for a v1. It doesn't have to support everything from the get go. Just having a redis adapter that we can use as a basic cache is a huge win.

> We might also be able to recognize special object fields (as we do now for id or _id, etc) for Redis types or options specification. Or, if set also accepted a recognized object, with two members: redis (with options) and data (the actual record data), or feathersOptions and feathersData. So for example, feathersOptions could indicate that the data is a Redis 'list' or 'set' and then accept an array in feathersData, or feathersOptions could indicate that the data is a Redis 'hash' and then accept an object full of fields and values in feathersData. I beleive this could be done in a backwards-compatible way with existing calls and code.

Handling special adapter params we kind of already do with Mongoose and [Sequelize](https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L38). We would have a `params.redis` object where you can pass DB specific options.

> Actually that linear search for paging may not be so bad. It's only a scan through all records to extract the IDs of the target page. That's probably still fast and uses little memory. But to provide strict (i.e. correct) $skip and $limit implementations, we'd need to scan the keys (IDs) from the beginning on each call. (That's what I'll do.)

That's what I was going to suggest for now and we can see how it works in practice. I think with a bit of finagling we could buffer the cursor and do the strict paging in memory in JS in the service if we really needed to but let's go with what you were thinking for now.

**Comment by daffl** [comment]
This has been kicking around for a little bit now. In order to keep our maintenance overhead (and issues like #2 and #5) down I'd either like to make the repository private until there is a releasable version and/or transfer it to @appurist if that's ok.

**Comment by appurist** [comment]
I think you should make delete it or make it private until such time as someone claims for active development.

My priorities took a dramatic turn and I haven't been able to contribute here and I'm unlikely to have a chance to come back to this.  I know it seems weird to delete it, but when something is stale it is often better to start from scratch next time someone comes along to champion the project.  I was mostly doing it as a learning experience for both feathers and redis and I have my own copy anyway should it ever make sense to revive it. If I do pick it back up again, even I might start over from one of the other feathers db adapters and by that point we'll probably all be using async/await and it would need a major overhaul anyway. ;) So... I'd probably just delete the repo and let someone start fresh if they want.

Although bear in mind the issues I describe above with trying to map redis into feathers service methods.  It doesn't really fit, and if you try, you'll probably eliminate most of the features of redis _and_ have an inefficient access to it.  Private or delete, I won't be offended at all either way. And I'll have a copy should you ever want it.

**Comment by daffl** [comment]
Sounds good and thank you very much for the work you put in @appurist! It's too bad there wasn't an easy way to get it to play nicely as a full fledged adapter.
