### ISSUE TITLE
Can not get featherjs redis

### ISSUE THREAD

**Issue by dattq6** [feathersjs-ecosystem/feathers-redis#5]
I have a problem regarded to get featherjs redis. When i run `npm install feathers-redis --save` in command line. It was through out this error:

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "feathers-redis" "--save"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/feathers-redis
npm ERR! 404
npm ERR! 404  'feathers-redis' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dattq6/MCDATA/VideoStreaming/server/npm-debug.log
```
Please tell me, how can i get featherjs redis?

**Comment by marshallswain** [comment]
It's not on npm, yet.  There are challenges to adapting the Feathers query syntax to the way Redis is used.  See the other issues for more details.  As a result, it has not been published and there is not currently a planned release date until somebody comes up with a good solution to the problems outlined in the other issues.

**Comment by daffl** [comment]
See discussion in https://github.com/feathersjs/feathers-redis/issues/4#issuecomment-306995921
